[tool.bumpversion]
current_version = "0.2.7"
search = "{current_version}"
replace = "{new_version}"

regex = true
allow_dirty = false
tag = true
tag_name = "v{new_version}"
tag_message = "Release {new_version}"
commit = true
message = "Bump version: {current_version} → {new_version}"

sign_tags = false
ignore_missing_version = false
ignore_missing_files = false

moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[tool.bumpversion.parts.pre_l]
values = ["dev", "alpha", "beta", "rc", "final"]
optional_value = "final"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "purrfectmeow/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[[tool.bumpversion.files]]
filename = "uv.lock"
search = 'name = "purrfectkit"\nversion = "{current_version}"'
replace = 'name = "purrfectkit"\nversion = "{new_version}"'
