from typing import List, Optional, Literal

from purrfectmeow.konja.splitter import Splitter

class Kornja:
    """
    A flexible interface for text segmentation based on tokenization or custom separation.

    This class provides a unified API for splitting large text inputs into smaller, manageable chunks using either
    token-based or separate-based strategies. It supports configuration of chunk size, overlap, and model-specific
    parameters for token-aware splitting, as well as simple string-based segmentation for more structured inputs.        
    """
    @staticmethod
    def chunking(
        text: str,
        splitter: Optional[Literal["token", "separate"]] = "token",
        **kwargs
    ) -> List[str]:
        """
        Handles text chunking with token or separate-based splitting.

        Parameters
        ----------
        text : str
            The input text to be chunked.
        splitter : str, optional
            The type of splitter to use for chunking. Must be either 'token' or 'separate'.
        **kwargs : dict
            Additional parameters for the splitter:
            
            For 'token' splitter:
                model_name : str, optional
                    Name of the model for token-based splitting.
                chunk_size : int, optional
                    Maximum size of each chunk in tokens.
                chunk_overlap : int, optional
                    Number of overlapping tokens between chunks.
            
            For 'separate' splitter:
                chunk_separator : str, optional
                    String used to split the text.

        Returns
        -------
        List[str]
            A list of text chunks generated by the specified splitter.

        Raises
        ------
        ValueError
            If `splitter` is not 'token' or 'separate', or if required parameters
            (`model_name` for 'token', `chunk_separator` for 'separate') are invalid or empty.

        Examples
        --------
        >>> text = "This is a sample text.\\n\\nAnother paragraph."
        >>> Kornja.chunking(text, splitter="separate", chunk_separator="\\n\\n")
        ['This is a sample text.', 'Another paragraph.']
        >>> Kornja.chunking(text, splitter="token", model_name="text-embedding-ada-002", chunk_size=10)
        ['This is a', 'sample text.', 'Another', 'paragraph.']
        """
        match splitter:
            case "token":
                model_name = kwargs.get("model_name", "text-embedding-3-large")
                chunk_size = kwargs.get("chunk_size", 500)
                chunk_overlap = kwargs.get("chunk_overlap", 0)

                if not model_name or not isinstance(model_name, str) or not model_name.strip():
                    raise ValueError("model_name must be a non-empty string for token splitter")
                sptr = Splitter.create_token_splitter(model_name, chunk_size, chunk_overlap)

            case "separate":
                separator = kwargs.get("chunk_separator") or kwargs.get("separator", "\n\n")
                
                if not isinstance(separator, str) or separator == "":
                    raise ValueError("separator must be a non-empty string for separator splitter")
                sptr = Splitter.create_separate_splitter(separator)
                
            case _:
                raise ValueError(f"Invalid splitter type: {splitter}. Must be 'token' or 'separate'.")

        chunks = sptr.split_text(text)
        return chunks