# name: Docker Image

# on:
#   push:
#     tags: [ 'latest', 'v*' ]

# jobs:
#   check-branch:
#     runs-on:
#       - self-hosted
#       - ${{ vars.SERVER_RUNNER_02 }}
#       - ${{ vars.PROJECT_NAME }}
#     outputs:
#       valid_branch: ${{ steps.set-branch-valid.outputs.valid }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v5
#         with:
#           fetch-depth: 0

#       - name: Check if tag is from ${{ vars.MAIN_BRANCH }}branch
#         id: set-branch-valid
#         run: |
#           echo "Checking if tag ${{ github.ref_name }} is from ${{ vars.MAIN_BRANCH }}..."
#           TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref_name }})

#           if git merge-base --is-ancestor $TAG_COMMIT origin/${{ vars.MAIN_BRANCH }}; then
#             echo "Tag is from ${{ vars.MAIN_BRANCH }} branch."
#             echo "valid=true" >> $GITHUB_OUTPUT
#           else
#             echo "Tag is NOT from ${{ vars.MAIN_BRANCH }} branch."
#             echo "valid=false" >> $GITHUB_OUTPUT
#           fi

  # build-image:
  #   runs-on:
  #     - self-hosted
  #     - ${{ vars.SERVER_RUNNER_02 }}
  #     - ${{ vars.PROJECT_NAME }}
  #   needs: check-branch
  #   if: needs.check-branch.outputs.valid_branch == 'true'
  #   outputs:
  #     image_tag: ${{ steps.set-image-tag.outputs.tag }}

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v5

  #     - name: Set image tag
  #       id: set-image-tag
  #       run: |
  #         echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT

  #     - name: Build Docker image
  #       run: |
  #         IMAGE_NAME=${{ vars.IMAGE_NAME }}
  #         TAG=${{ github.ref_name }}
  #         echo "Building Docker image: $IMAGE_NAME:$TAG"
  #         docker build -t $IMAGE_NAME:$TAG .

  #     - name: Save Docker image as artifact
  #       run: |
  #         docker save ${{ vars.IMAGE_NAME }}:${{ github.ref_name }} -o ${{ vars.IMAGE_NAME }}_${{ github.ref_name }}.tar

  #     - name: Upload Docker image artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: docker-image
  #         path: ${{ vars.IMAGE_NAME }}_${{ github.ref_name }}.tar

  # push-image:
  #   runs-on:
  #     - self-hosted
  #     - ${{ vars.SERVER_RUNNER_02 }}
  #     - ${{ vars.PROJECT_NAME }}
  #   needs: build-image
  #   if: needs.check-branch.outputs.valid_branch == 'true'

  #   steps:
  #     - name: Download Docker image artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: docker-image
  #         path: .

  #     - name: Load Docker image
  #       run: |
  #         docker load -i ${{ vars.IMAGE_NAME }}_${{ needs.build-image.outputs.image_tag }}.tar

  #     - name: Log in to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ vars.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Tag and push
  #       run: |
  #         IMAGE_NAME=${{ vars.IMAGE_NAME }}
  #         TAG=${{ needs.build-image.outputs.image_tag }}

  #         docker tag $IMAGE_NAME:$TAG ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$TAG
  #         docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$TAG

  #         docker tag $IMAGE_NAME:$TAG ${{ vars.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$TAG
  #         docker push ${{ vars.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$TAG
